"use client";

import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        />
        <script
          src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
          integrity="sha384-9mGPKin8e58Wd0t+cAVHt0wFTovD+swFv8YfOyO1N0lX9d/5Qq3zg5h5DZK5/5Aj"
          crossOrigin=""
        ></script>
      </Head>
      <body>{children}</body>
    </html>
  );
}
